linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: gortc.io
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - commentedOutCode
      - sloppyReassign

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Ease some gocritic warnings on test files.
    - path: _test\.go
      text: "(unnamedResult|exitAfterDefer|unlambda)"
      linters:
        - gocritic

    - path: ^cmd/
      linters:
        - gocyclo
    - path: ^cmd/
      text: "(unnamedResult|exitAfterDefer)"
      linters:
        - gocritic

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - scopelint

run:
  skip-dirs:
    - e2e
    - fuzz
    - testdata
    - api
